#!/usr/bin/python
from sys import exit
import subprocess


compile_languages = ['en,node,nono','es,node,nono','de,nono','no,node','dk,node']
compile_options = ['it','tea','pol','ant','tea,ant','tea,pol,ant','tea,pol,ant,it']


beautify_dic = {
	'en' : 'English',
	'es' : 'Spanish',
	'no' : 'Norwegian',
	'dk' : 'Danish',
	'de' : 'German',
	'it' : 'IT',
	'tea' : 'Teaching',
	'pol' : 'Political',
	'ant' : 'Anthropology'
}


def beautify_abbreviation(abbreviation):
	return_string = ""
	for item in abbreviation.split(","):
		if item in beautify_dic:
			return_string += beautify_dic[item] + " + "
	return return_string.strip(' +')


html_output = "<html><head><title>My CVs</title></head>"
html_output +="<body><h1>My CVs</h1>"

from tempfile import mkdtemp
from shutil import rmtree

tmpdir = mkdtemp()
for compile_language in compile_languages:
	html_output += f"<h3>{beautify_abbreviation(compile_language)}</h3>"
	for compile_option in compile_options:
		jobname = compile_language.split(',')[0]+'_'+compile_option.replace(',','_')
		subprocess.run(f"lualatex  --interaction=nonstopmode --jobname={jobname} --output-directory={tmpdir} \"\\def\\UseOption{{ {compile_language},{compile_option}}}\\input{{contents}}\"", shell=True)
		html_output += f"<p><a target='_parent' href='{jobname}.pdf'>{beautify_abbreviation(compile_option)}</a></p>"
html_output += "</body></html>"

html_file = open('../index.html','w')
html_file.write(html_output)
html_file.close()

subprocess.run(f"mv {tmpdir}/*pdf ../", shell=True)

rmtree(tmpdir)
